/**
 * Dashboard Home — Ledger
 * =======================
 * Maps to Stitch screen: "Home — Ledger" (3717694b)
 * 
 * This is the primary briefing screen with:
 * - KPI row (live data from DB)
 * - AI morning briefing
 * - Recent activity feed
 * - Command bar for AI chat
 * 
 * Full implementation in Step 5 (AI Chat) and Step 10 (KPIs).
 * For now: structural skeleton with design-accurate styling.
 */
import { BarChart3, Users, Target, Clock, TrendingUp, Sparkles } from "lucide-react";

export default function DashboardPage() {
  return (
    <div>
      {/* Page Header */}
      <div className="mb-8">
        <div className="text-stamp-label text-on-surface-variant mb-2">
          DASHBOARD · HOME
        </div>
        <h1 className="text-headline-md text-on-surface">
          Good afternoon, Kinnari
        </h1>
        <p className="text-body-md text-on-surface-variant mt-1">
          Here&apos;s your Ledger briefing for today.
        </p>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-4 gap-4 mb-8">
        {[
          { label: "ACTIVE PIPELINE", value: "₹3.4L", icon: TrendingUp, accent: "text-primary-container" },
          { label: "OPEN OPPORTUNITIES", value: "4", icon: Target, accent: "text-secondary" },
          { label: "PENDING TASKS", value: "4", icon: Clock, accent: "text-on-tertiary-container" },
          { label: "CONTACTS", value: "8", icon: Users, accent: "text-primary-container" },
        ].map((kpi) => (
          <div key={kpi.label} className="card-index p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-stamp-label text-on-surface-variant">
                {kpi.label}
              </span>
              <kpi.icon className={`w-4 h-4 ${kpi.accent}`} strokeWidth={1.5} />
            </div>
            <div className="text-headline-sm text-on-surface">{kpi.value}</div>
          </div>
        ))}
      </div>

      {/* AI Briefing Card */}
      <div className="card-memo card-memo-blue p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-primary-container" strokeWidth={1.5} />
          <span className="text-stamp-label text-primary-container">
            LEDGER AI BRIEFING
          </span>
        </div>
        <div className="text-body-md text-on-surface space-y-2">
          <p>📋 <strong>3 tasks due this week</strong> — Prepare demo for Rahul (Thu), send proposal to Priya (Fri), follow up with Aditya.</p>
          <p>💰 <strong>Pipeline update</strong> — GrowthCo deal (₹1.25L) is in proposal stage and needs attention.</p>
          <p>🔥 <strong>Alert:</strong> Rahul&apos;s demo is in 2 days. Demo materials haven&apos;t been shared yet.</p>
        </div>
        <div className="mt-4 pt-4 border-t border-hairline">
          <span className="text-utility-mono text-on-surface-variant">
            Generated by Ledger · Today at 9:00 AM
          </span>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="card-index p-6">
        <div className="flex items-center gap-2 mb-4">
          <BarChart3 className="w-4 h-4 text-on-surface-variant" strokeWidth={1.5} />
          <span className="text-stamp-label text-on-surface-variant">
            RECENT ACTIVITY
          </span>
        </div>
        <div className="space-y-3">
          {[
            { time: "10:30 AM", text: "Rahul Sharma sent a WhatsApp message", type: "WHATSAPP" },
            { time: "9:15 AM", text: "Ledger sent AI follow-up to Meera Joshi", type: "AI" },
            { time: "Yesterday", text: "Discovery call with Aditya Kumar (12 min)", type: "CALL" },
            { time: "Jun 28", text: "Email from Priya Mehta — Enterprise CRM Proposal", type: "EMAIL" },
          ].map((item, i) => (
            <div key={i} className="flex items-start gap-3 py-2 border-b border-hairline last:border-0">
              <span className="text-utility-mono text-on-surface-variant w-20 shrink-0 pt-0.5">
                {item.time}
              </span>
              <span className="text-body-sm text-on-surface flex-1">{item.text}</span>
              <span className={`stamp-badge text-[9px] ${
                item.type === "WHATSAPP" ? "text-secondary border-secondary" :
                item.type === "AI" ? "text-primary-container border-primary-container" :
                item.type === "CALL" ? "text-on-tertiary-container border-on-tertiary-container" :
                "text-on-surface-variant border-on-surface-variant"
              }`}>
                {item.type}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
