/**
 * Dashboard Home — Ledger
 * =======================
 * Maps to Stitch screen: "Home — Ledger" (3717694b)
 * 
 * This is the primary briefing screen with:
 * - KPI row (live data from DB)
 * - AI morning briefing (hardcoded until Phase C)
 * - Recent activity feed (real DB data)
 * - Command bar for AI chat
 */
import { BarChart3, Users, Target, Clock, TrendingUp, Sparkles } from "lucide-react";
import { getDashboardKPIs, getRecentActivity } from "@/lib/db/scoped";
import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db/prisma";

/** Format Indian Rupee amounts with lakhs notation */
function formatINR(amount: number): string {
  if (amount >= 100000) {
    const lakhs = amount / 100000;
    return `₹${lakhs % 1 === 0 ? lakhs.toFixed(0) : lakhs.toFixed(1)}L`;
  }
  const s = amount.toString();
  if (s.length <= 3) return `₹${s}`;
  const last3 = s.slice(-3);
  const remaining = s.slice(0, -3);
  const grouped = remaining.replace(/\B(?=(\d{2})+(?!\d))/g, ",");
  return `₹${grouped},${last3}`;
}

/** Format relative time for activity feed */
function formatRelativeTime(date: Date): string {
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) {
    return date.toLocaleTimeString("en-IN", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });
  }
  if (diffDays === 1) return "Yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  return date.toLocaleDateString("en-IN", { month: "short", day: "numeric" });
}

export default async function DashboardPage() {
  const session = await getSession();
  if (!session) {
    redirect("/login");
  }

  const [kpis, recentActivity, user] = await Promise.all([
    getDashboardKPIs(session.tenantId),
    getRecentActivity(session.tenantId),
    prisma.user.findUnique({
      where: { id: session.userId },
      select: { name: true },
    }),
  ]);

  const firstName = user?.name ? user.name.split(" ")[0] : "user";

  const kpiCards = [
    { label: "ACTIVE PIPELINE", value: formatINR(kpis.activePipeline), icon: TrendingUp, accent: "text-primary-container" },
    { label: "OPEN OPPORTUNITIES", value: String(kpis.openOpportunities), icon: Target, accent: "text-secondary" },
    { label: "PENDING TASKS", value: String(kpis.pendingTasks), icon: Clock, accent: "text-on-tertiary-container" },
    { label: "CONTACTS", value: String(kpis.totalContacts), icon: Users, accent: "text-primary-container" },
  ];

  return (
    <div>
      {/* Page Header */}
      <div className="mb-8">
        <div className="text-stamp-label text-on-surface-variant mb-2">
          DASHBOARD · HOME
        </div>
        <h1 className="text-headline-md text-on-surface">
          Good afternoon, {firstName}
        </h1>
        <p className="text-body-md text-on-surface-variant mt-1">
          Here&apos;s your Ledger briefing for today.
        </p>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-4 gap-4 mb-8">
        {kpiCards.map((kpi) => (
          <div key={kpi.label} className="card-index p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-stamp-label text-on-surface-variant">
                {kpi.label}
              </span>
              <kpi.icon className={`w-4 h-4 ${kpi.accent}`} strokeWidth={1.5} />
            </div>
            <div className="text-headline-sm text-on-surface">{kpi.value}</div>
          </div>
        ))}
      </div>

      {/* AI Briefing Card — hardcoded until Phase C wires real AI */}
      <div className="card-memo card-memo-blue p-6 mb-6">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-primary-container" strokeWidth={1.5} />
          <span className="text-stamp-label text-primary-container">
            LEDGER AI BRIEFING
          </span>
        </div>
        <div className="text-body-md text-on-surface space-y-2">
          <p>📋 <strong>{kpis.pendingTasks} tasks pending</strong> — Check your tasks page for details.</p>
          <p>💰 <strong>Pipeline update</strong> — {kpis.openOpportunities} open opportunities worth {formatINR(kpis.activePipeline)} in active pipeline.</p>
          <p>🔥 <strong>Alert:</strong> Review your inbox for recent customer conversations.</p>
        </div>
        <div className="mt-4 pt-4 border-t border-hairline">
          <span className="text-utility-mono text-on-surface-variant">
            Generated by Ledger · Today at 9:00 AM
          </span>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="card-index p-6">
        <div className="flex items-center gap-2 mb-4">
          <BarChart3 className="w-4 h-4 text-on-surface-variant" strokeWidth={1.5} />
          <span className="text-stamp-label text-on-surface-variant">
            RECENT ACTIVITY
          </span>
        </div>
        <div className="space-y-3">
          {recentActivity.map((item, i) => (
            <div key={i} className="flex items-start gap-3 py-2 border-b border-hairline last:border-0">
              <span className="text-utility-mono text-on-surface-variant w-20 shrink-0 pt-0.5">
                {formatRelativeTime(item.time)}
              </span>
              <span className="text-body-sm text-on-surface flex-1">{item.text}</span>
              <span className={`stamp-badge text-[9px] ${
                item.type === "WHATSAPP" ? "text-secondary border-secondary" :
                item.type === "AI" ? "text-primary-container border-primary-container" :
                item.type === "CALL" ? "text-on-tertiary-container border-on-tertiary-container" :
                "text-on-surface-variant border-on-surface-variant"
              }`}>
                {item.type}
              </span>
            </div>
          ))}
          {recentActivity.length === 0 && (
            <div className="text-center py-6 text-body-sm text-on-surface-variant">
              No recent activity.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
